name: piramal_channel_partner
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.3+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: 4.0.6
  provider: ^6.0.5
  connectivity_plus: 2.3.6+1
  page_transition: ^2.0.9
  animations: 2.0.1
  fluttertoast: ^8.1.1
  pie_chart: ^5.3.2
  url_launcher: 6.1.5
  logger: 1.1.0
  shimmer: 2.0.0
  linter: ^1.28.0
  flutter_swiper: ^1.1.6
  shared_preferences: ^2.0.15
  cached_network_image: 3.2.2
  progress_dialog: 1.2.4
  file_picker: 5.2.1
  image_picker: ^0.8.6
  carousel_slider: 4.0.0
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.15
  permission_handler: ^10.2.0
  slide_countdown: ^0.3.4
  liquid_progress_indicator: ^0.4.0
  device_info_plus: ^8.1.0
  package_info_plus: ^3.0.3
  youtube_player_flutter: ^8.1.2
  marquee: 2.2.0
  webview_flutter: ^4.0.7
  video_player: ^2.6.1
  syncfusion_flutter_pdfviewer: 20.3.47
  path_provider: ^2.0.11
  share_plus: ^6.3.2
  firebase_core: 2.8.0
  firebase_messaging: 14.3.0
  flutter_local_notifications: 13.0.0
  awesome_notifications: ^0.6.21
  pinput: ^2.2.31
  external_path: ^1.0.3
  sms_autofill: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Calibri
      fonts:
        - asset: assets/fonts/calibri_bold.ttf
        - asset: assets/fonts/calibri_light.ttf
        - asset: assets/fonts/calibri_regular.ttf
